language: node_js
sudo: false

node_js:
  # Node.js 0.10 support has been dropped in PostHTML
  #- "0.10"
  - "0.12"
  - "4"
  - "6"

after_success:
  - npm run coverage
  - npm i codecov
  - codecov -f coverage/coverage.json

notifications:
  email:
    on_success: never
