language: node_js
sudo: false

node_js:
  # Node.js 0.10 support has been dropped in PostHTML
  #- "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
